name = "ReferenceFrameRotations"
uuid = "74f56ac7-18b3-5285-802d-d4bd4f104033"
license = "MIT"
desc = "3D rotations of coordinate frames"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.5.3"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Crayons = "≥ 1.0.0"
StaticArrays = "≥ 0.9.2"
julia = "≥ 1.0.0"

[targets]
test = ["Test"]
